# This is a basic workflow to help you get started with Actions

name: TpTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tp_tests:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: rhoward-howqa/github-action@master
      with:
        project_id: 'jrKiet1cHEyKBTcZMmLoMg'
        job_id: 'heb20uUMlkSeTvaM8K8fFg'
        authorisation_token: 'wiaj2NlksX-SGf6VJctehppP1PLlYNZ5q4FNiQVY7wY1'        
